dockerImageAndWorkDir: &dockerImageAndWorkDir
  working_directory: ~/user-ms
  docker: 
    - image: circleci/node:7.10

version: 2.0
jobs:
  install-dependencies:
    <<: *dockerImageAndWorkDir
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{checksum "package-lock.json"}}
      - run:
          name: 'Set approval to false'
          command: echo "false" > approval
      - run:
          name: 'Installing dependencies'
          command: npm install
      - save_cache:
          key: v1-{{checksum "package-lock.json"}}
          paths:
              - ~/user-ms/node_modules
      - persist_to_workspace:
          root: ~/user-ms
          paths:
            - .
  approve:
    <<: *dockerImageAndWorkDir
    steps:
      - attach_workspace:
          at: ~/user-ms
      - checkout
      - run:
          name: 'Save a file with new content'
          command: echo "true" > approval
      - persist_to_workspace:
          root: ~/user-ms
          paths:
            - .
  wait:
    <<: *dockerImageAndWorkDir
    steps:
      - run:
          name: 'Sleep for 1m'
          command: sleep 1m
      - attach_workspace:
          at: ~/user-ms
      - checkout
      - run:
          name: 'Check the file contents'
          command: sh deployments/move.sh
      
  test-and-lint:
    <<: *dockerImageAndWorkDir
    steps:
      - attach_workspace:
          at: ~/user-ms
      - checkout
      - restore_cache:
          keys:
          - v1-{{checksum "package-lock.json"}}
      - run:
          name: 'Running unit testcases'
          command: npm run test
      - run:
          name: 'Running lint'
          command: 'npm run lint'
workflows:
  version: 2
  test-and-lint:
    jobs:
      - install-dependencies
      - wait:
          requires: 
              - install-dependencies
      - hold:
          type: approval
          requires: 
              - install-dependencies
      - approve:
          requires:
              - hold
      - test-and-lint:
          requires:
              - wait
              - approve